### ISSUE TITLE
Question: Advice for how to implement global filters in 1.0

### ISSUE THREAD

**Issue by robrez** [Polymer/polymer-expressions#63]
In .5, we could write global filters:
```
PolymerExpressions.prototype.uppercase = function(input) {
  if (input) {
    return input.toUpperCase();
  }
};
```
And bind data piped through the filter `{{data | uppercase}}`

In 1.0, we'd do something like this: `{{uppercase(data)}}`.

I'm wondering if there's a recommended approach to making the function (ie: uppercase) available to all custom-elements in my project?

**Comment by donwojtallo** [comment]
I want to know this too! 
I want to bring back i18n functionality in my app back to live. It was working well with Polymer expressions.
Anyway, creating a custom element could be a good workaround. Simplified example:
```
<dom-module id="uppercase-element">

	<template>
		<content></content>
	</template>
		
	<script>
		Polymer({
			is: 'uppercase-element',
			ready: function () {
				var element = this;
				var observer = new MutationObserver(function (mutations) {
					element.innerHTML = element.innerHTML.toUpperCase();
				}).observe(this, { childList: true, subtree: true, characterData: true });
			}
		});
	</script>
	
</dom-module>
```
And you use it like this:
```
<uppercase-element>Example text</uppercase-element>
```
I think that this approach does not solve the problem, but might help in some situations.

**Comment by robrez** [comment]
Yeah that could certainly work for some scenarios.

I was going to take a look at mixins - but the 1.0 docs don't seem to mention them very much.

In .5 they are documented here:
https://www.polymer-project.org/0.5/docs/polymer/helpers.html#using-mixins

**Comment by techniq** [comment]
@robrez I'm pretty sure mixins became [behaviors](https://www.polymer-project.org/1.0/docs/devguide/behaviors.html) so you might want to look there

**Comment by donwojtallo** [comment]
I already tried to use behaviors but it looks like the computed binding function cannot be shared.
According to docs:
> A behavior can define lifecycle callbacks , declared properties, default attributes, observers listeners.

**Comment by techniq** [comment]
:-1:

**Comment by techniq** [comment]
@donwojtallo Could you create a behavior with a lifecycle callback on `created` that adds the functions to `this` within the callback?

Or possibly brute force it by adding the methods to `Polymer.base` or even `window` (dirty I know)?

**Comment by robrez** [comment]
The api docs show that mixin(target, source) still exists...
http://polymer.github.io/polymer/

**Comment by donwojtallo** [comment]
Check this out:
```
var FiltersBehavior = {
	created: function() {
		this.uppercase = function(text) {
			return text.toUpperCase();
		}
	}
}
```
It declares a computed binding function while creating an element. To use it:
```
<dom-module id="my-element">
	
	<template>
		<div>{{uppercase('test')}}</div>
	</template>
		
	<script>
		Polymer({
			is: 'my-element',
			behaviors: [FiltersBehavior]
		});
	</script>
	
</dom-module>
```
:)

**Comment by robrez** [comment]
@donwojtallo Awesome! That's probably approaching the correct approach.

I think I read somewhere that modifying the prototype in created is not ideal.

It still works if you modify it as follows:
```
  <script>
    var FiltersBehavior = {
        uppercase: function(input) {
            if (input) {
                return input.toUpperCase();
            } else {
                return input;
            }
        }
    };
  </script>
```

**Comment by donwojtallo** [comment]
Weird, I though that this wouldn't work and now it's working. Maybe I made a typo while testing...
Anyway, problem solved for me. Thank you all!

**Comment by techniq** [comment]
:+1:

**Comment by robrez** [comment]
Closing, See #1223
